### 1. Admin Login (Get Token)
POST http://localhost:5000/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###

### ⚠️ Copy token from above response and paste below
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc0MTk0OTMyLCJleHAiOjE3NzQyMDIxMzJ9.sEdHPJd99h-EjfUjkawCwGkEHitsWhJiXlhygomN1yQ
###

### 2. Add Movie
POST http://localhost:5000/movies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Ustaad Bhagat Singh",
  "year": 1990,
  "posterImageUrl": "https://example.com/poster.jpg",
  "bannerImageUrl": "https://example.com/banner.jpg",
  "overview": "Avengers fight Thanos.",
  "trailerUrl": "https://youtube.com/embed/6ZfuNTqbHE8",
  "director": "Anthony Russo, Joe Russo",
  "writer": "Christopher Markus, Stephen McFeely",
  "runTime": 149,
  "releaseDate": "1990-03-19",
  "rating": "PG-13"
}

###

### 3. Get All Movies (Sorted by Date)
GET http://localhost:5000/movies

###

### 4. Get Single Movie (replace ID)
GET http://localhost:5000/movies/00156e58-3dc8-407e-9526-5ff69230ad7f

###

### 5. Update Movie
PUT http://localhost:5000/movies/00156e58-3dc8-407e-9526-5ff69230ad7f
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "They Call Him OG 2",
  "year": 2028,
  "posterImageUrl": "https://example.com/poster2.jpg",
  "bannerImageUrl": "https://example.com/banner2.jpg",
  "overview": "Updated overview.",
  "trailerUrl": "https://youtube.com/embed/6ZfuNTqbHE8",
  "director": "Russo Brothers",
  "writer": "Marvel Studios",
  "runTime": 150,
  "releaseDate": "2028-04-27",
  "rating": "PG-13"
}

###

### 6. Delete Single Movie
DELETE http://localhost:5000/movies/b02e57a1-1f0e-46a3-bad6-23a97c834691
Authorization: Bearer {{token}}

###

### 7. Delete All Movies
DELETE http://localhost:5000/movies/all
Authorization: Bearer {{token}}